#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'steadylab','console_scripts','sub_zed_left_image'
__requires__ = 'steadylab'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('steadylab', 'console_scripts', 'sub_zed_left_image')()
    )
